name: Docker SBT
on:
  push:
    branches:
      - master
jobs:
  Publish_sbt_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: ls -a

