name: Docker SBT
on:
  push:
    branches:
      - master
jobs:
  Publish_sbt_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
#      - name: checkout
#        uses: actions/checkout@v2
      - name: echo
        run: |
          ls
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
          export TEST001=Miuler
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./jdk-11-slim
#          push: false
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
      - name: echo
        run: |
          ls
          echo "TEST001: $TEST001"
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"

