name: Docker SBT
on:
  push:
    branches:
      - master
jobs:
  Publish_sbt_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          pwd
          ls -a
          ls -a ..
          ls -a ../..
      - name: checkout
        uses: actions/checkout@v2
      - name: List
        run: |
          pwd
          ls -a
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

